### ISSUE TITLE
3D scatter: markers are not displayed

### ISSUE THREAD

**Issue by vfuga** [JuliaPlots/Makie.jl#1184] opened 2021-08-01 08:29 UTC
## I'm totally newbie with Julia Lang, anyway...
println("Hi Everybody! Could you help with this?")
##
using Pkg
Pkg.activate(".")
Pkg.add("GLMakie")
##
using GLMakie
##
x = randn(1000) .* 10
y = randn(1000) .* 10
z = randn(1000) .* 10
##
scine1worksFine = lines(x, y, z, linewidth = 1, markersize=10, color=:red)   <==== works fine!
##
scine2DoesNotWork = scatter(x, y, z, markersize = 10, color = :red)   ## <============== DOES NOT WORK
##
println("But,... where are the markers?.. graph is empty... :(")
##

Windows 10 Pro 21H1 19043.1151
julia 1.6.2

pkg> status
      Status `D:\DataScience\Julia-Projects\Ex1\Project.toml`
  [e9467ef8] GLMakie v0.4.4
  [324d217c] ReferenceTests v0.9.7

**Comment by SimonDanisch** [comment] 2021-11-02 12:45
Duplicate of: https://github.com/JuliaPlots/Makie.jl/issues/994

**Closed by SimonDanisch** 2021-11-02 12:45 UTC
