### ISSUE TITLE
Makie crashing when performing several zooms in

### ISSUE THREAD

**Issue by nandoconde** [JuliaPlots/Makie.jl#909] opened 2021-04-12 16:12 UTC
A MWE in my computer:

```julia
using GLMakie

x = 1:10000
F = @. x^2

lines(x, F)
```

After zooming in on the same zone seven or eight times, the window freezes and then proceeds to crash `julia.exe`.

**Comment by jkrumbiegel** [comment] 2021-04-12 16:31
you keep zooming? at some point the limits are so small that we run into floating point inaccuracies, and it could be that some code really doesn't like that. although crashing is pretty extreme. no usable stacktrace?

**Comment by nandoconde** [comment] 2021-04-13 07:23
I should clarify: this only happens with rectangular zoom, wheel zoom seems OK.

Unfortunately, there is no trace, because the `julia.exe` process just stops, nothing is printed out to the REPL.

**Comment by SebastianM-C** [comment] 2021-04-13 08:00
You could try launching julia from the terminal / cmd. This way you should see the errors even after the julia process crashes.

**Comment by nandoconde** [comment] 2021-04-13 09:27
I tried lunching it with `cmd`, and nothing. 

The typical Windows warning "The `julia.exe` process is not responding: Wait/Close" appears after the 13th rectangular zoom, and when I click "Close", the only thing remaining is the `cmd` shell:

```dos
julia>

julia> lines(x, F)

julia>
C:\Users\ferna>
```

**Comment by jkrumbiegel** [comment] 2021-04-15 05:39
what do you expect to see after 13 zooms? are you not in unusable float32 area then? which means ticks are breaking down, plots are weirdly quantized, etc. it's not good that it crashes, obviously, i'm just wondering how much of a "normal" workflow this is

**Comment by nandoconde** [comment] 2021-04-15 14:13
Not at all a workflow for anything, it was just me being bored while waiting for a simulation to finish 😄

**Comment by nandoconde** [comment] 2021-04-19 10:23
More on this, in case you want to do something about it. As a I said, I don't see it as priority at all, but it is good to know that it happens.

I think the problem comes when there is no "actual" point being plot on the scene, just the line interpolated between two of them, because I managed to get an error of `Colon` operator in Base when trying to zoom.

**Comment by SimonDanisch** [comment] 2021-11-02 13:07
Likely duplicate of: https://github.com/JuliaPlots/Makie.jl/issues/1040

**Closed by SimonDanisch** 2021-11-02 13:07 UTC
