### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'wgl_camera')

### ISSUE THREAD

**Issue by zhulunwu** [JuliaPlots/Makie.jl#2192] opened 2022-08-02 08:18 UTC
I run examples from https://makie.juliaplots.org/v0.15.2/tutorials/basic-tutorial/
replace CairoMakie by WGLMakie and JS exception occurs:
...TypeError: Cannot read properties of undefined (reading 'wgl_camera') ...

here is the code:
`using WGLMakie
f=Figure() ;
ax=Axis(f[1,1])`

WGLMakie version is v0.6.12, both on windows and fedoras 35

**Comment by SimonDanisch** [comment] 2022-08-03 09:26
Duplicate of: https://github.com/JuliaPlots/Makie.jl/issues/1546

**Closed by SimonDanisch** 2022-08-03 09:26 UTC
