### ISSUE TITLE
Multiple windows

### ISSUE THREAD

**Issue by MartinOtter** [JuliaPlots/Makie.jl#719] opened 2020-10-13 10:31 UTC
Is there a possibility to generate multiple windows with Makie, e.g. scene1=Scene(); scene2=Scene() and then have two windows. When I do this on my Windows 10 machine, only **one** window is shown (either scene1 or scene2, depending on the last command).

**Comment by SimonDanisch** [comment] 2020-10-13 10:54
Duplicate of: https://github.com/JuliaPlots/Makie.jl/issues/188

**Closed by SimonDanisch** 2020-10-13 10:54 UTC
