### ISSUE TITLE
Saving a contourf figure to PDF produces too large a file

### ISSUE THREAD

**Issue by briochemc** [JuliaPlots/Makie.jl#834] opened 2021-02-02 02:44 UTC
I think the current `contourf` implementation is too greedy in some way, such that the PDF outputs — which are beautiful — take too much memory.

Below I compare making a plot and saving it to PDF with different "software". The plots are all similar, but the Makie PDF (CairoMakie backend) is about 27 times bigger than the other PDFs (2.7MB vs ~100KB). See table below:

| software | output screenshot | PDF file | size |
| :-- | :-- | :-- | :-- |
| Makie.jl | <img width="925" alt="Screen Shot 2021-02-02 at 1 32 17 pm" src="https://user-images.githubusercontent.com/4486578/106544279-5f494a00-655b-11eb-865b-b37b3f4d69b7.png"> | [Makie_jl.pdf](https://github.com/JuliaPlots/Makie.jl/files/5908212/Makie_jl.pdf) | 2.7 MB |
| Plots.jl | <img width="1077" alt="Screen Shot 2021-02-02 at 1 32 38 pm" src="https://user-images.githubusercontent.com/4486578/106544277-5eb0b380-655b-11eb-954d-0d2af84ba7fc.png"> | [Plots_jl.pdf](https://github.com/JuliaPlots/Makie.jl/files/5908216/Plots_jl.pdf) | 112 KB |
| Python | <img width="703" alt="Screen Shot 2021-02-02 at 1 32 45 pm" src="https://user-images.githubusercontent.com/4486578/106544276-5e181d00-655b-11eb-8084-367ab57f1400.png"> | [matplotlib.pdf](https://github.com/JuliaPlots/Makie.jl/files/5908215/matplotlib.pdf) | 106 KB |
| MATLAB | <img width="859" alt="Screen Shot 2021-02-02 at 1 32 52 pm" src="https://user-images.githubusercontent.com/4486578/106544271-5ce6f000-655b-11eb-8390-26ef387e2dc8.png"> | [MATLAB.pdf](https://github.com/JuliaPlots/Makie.jl/files/5908214/MATLAB.pdf) | 96 KB |

To be fair, it seems that the MATLAB code actually produces a rasterized image of the filled contours, which is cheating a bit, but the other ones (Plots.jl and matplotlib) don't, so I think these provide a fair comparison.

**Can the PDF output of `contourf` be somehow reduced in future releases?**

For reproducibility, below are the MWEs used to make each of these: 

- Makie.jl:

    ```julia
    using CairoMakie
    
    delta = 0.025
    
    x = y = -3.0:delta:3.01
    Z1 = @. exp(-x'^2 - y^2)
    Z2 = @. exp(-(x' - 1)^2 - (y - 1)^2)
    Z = 2(Z1 - Z2)
    
    levels = -2.0:0.1:2.0
    
    fig = Figure()
    ax = fig[1,1] = Axis(fig)
    co = contourf!(ax, x, y, Z, levels=levels)
    cbar = fig[1,2] = Colorbar(fig, co, width=30, tellwidth=true)
    
    save("Makie_jl.pdf", fig)
    ```

- Plots.jl:

    ```julia
    using Plots
    
    delta = 0.025
    
    x = y = -3.0:delta:3.01
    Z1 = @. exp(-x'^2 - y^2)
    Z2 = @. exp(-(x' - 1)^2 - (y - 1)^2)
    Z = 2(Z1 - Z2)
    
    levels = -2.0:0.1:2.0
    
    contourf(x, y, Z, levels=levels)
    
    savefig("Plots_jl.pdf")
    ```

- matplotlib / Python: 

    ```python
    import numpy as np
    import matplotlib.pyplot as plt
    
    delta = 0.025
    
    x = y = np.arange(-3.0, 3.01, delta)
    X, Y = np.meshgrid(x, y)
    Z1 = np.exp(-X**2 - Y**2)
    Z2 = np.exp(-(X - 1)**2 - (Y - 1)**2)
    Z = 2 * (Z1 - Z2)
    
    levels = np.arange(-2.0, 2.0, 0.1)
    
    fig, ax = plt.subplots()
    CS = ax.contourf(X, Y, Z, levels=levels)
    cbar = fig.colorbar(CS)
    
    plt.savefig("matplotlib.pdf")
    ```

- MATLAB:

    ```matlab
    delta = 0.025
    
    x = -3.0:delta:3.01
    y = x
    Z1 = exp(-x'.^2 - y.^2)
    Z2 = exp(-(x' - 1).^2 - (y - 1).^2)
    Z = 2 * (Z1 - Z2)
    
    levels = -2.0:0.1:2.0
    
    contourf(x, y, Z, levels)
    colorbar()
    
    print('MATLAB', '-dpdf')
    ```

(edit: had a typo in the siz of the make PDF in the table ~~27~~ -> 2.7 MB)

**Comment by ffreyer** [comment] 2021-02-02 09:20
The reason why it's so big is that `contourf` produces a mesh-plot which is then plotted triangle-by-triangle in CairoMakie. The good about this is that you can save any mesh plot (including meshscatter, surface and anything that depends on those) in a vectorized from, including 3d plots. The bad is, well, file size.

If I understand correctly `contourf` produces a bunch of lines, matching levels, which are interpreted as borders of polygons. These polygons are then triangulated (with holes) by GeometryBasics. I think Cairo allows for drawing any filled polygon, so we could skip the triangulation and instead just draw the raw polygons in the right order.

**Comment by jkrumbiegel** [comment] 2021-02-02 10:48
it used to be polys, I think Simon changed it to mesh because of some updating problem with poly. We didn't think about the file size issue. I think it should be possible to either change back to poly or to intercept fitting mesh calls in CairoMakie, although I'm not sure right now if we have access to the original signature, or only the converted one which would already be triangulated

**Comment by ffreyer** [comment] 2021-02-02 12:17
`poly` also lowers to a `mesh` call , so we'd need to intercept either way. But `poly` would be a good target to intercept

**Comment by jkrumbiegel** [comment] 2021-02-02 12:24
We're already dispatching specifically on `poly` because of this issue

**Comment by jkrumbiegel** [comment] 2021-02-02 20:51
I just did a local test where I used `poly` inside `contourf` again. I also needed to write an explicit method in CairoMakie for `Poly{<:AbstractVector{<:Polygon}}`. Looked like this and the pdf is 88kb in size:

<img width="708" alt="grafik" src="https://user-images.githubusercontent.com/22495855/106660721-a7d72680-65a0-11eb-99b5-7b5942e8b8ba.png">

Will need some cleaning up though, also I'm not sure if using poly inside contourf is difficult for dynamic plots or if it was just easier for Simon to implement it that way.

**Comment by jkrumbiegel** [comment] 2021-02-02 21:55
https://github.com/JuliaPlots/AbstractPlotting.jl/pull/622
https://github.com/JuliaPlots/CairoMakie.jl/pull/134

**Comment by briochemc** [comment] 2021-02-02 21:55
Nitpicking on the details, is there a way to avoid the thin white lines that are also visible in the colorbar?

**Comment by jkrumbiegel** [comment] 2021-02-02 21:57
that's out of our hands really, it's an antialiasing issue of whatever displays the vector graphics. every plotting tool's output suffers the same from it if you google around. I only introduced a "hack" to CairoMakie for heatmaps where I would slightly enlarge each tile so they overlapped. But I'm still not sure if that can't have edge cases. I only thought about the edge case where you have transparent colors and it checks for that

**Comment by jkrumbiegel** [comment] 2021-02-02 21:59
that was this pr https://github.com/JuliaPlots/CairoMakie.jl/pull/105 because the white line issue annoyed me as well

**Comment by jkrumbiegel** [comment] 2021-02-02 22:01
if you really want to get rid of it in a contourf plot, the easiest might be to plot really thin contour lines on top with the correct color scheme, although that also squarely falls into the "hack" category..

**Comment by briochemc** [comment] 2021-02-02 22:17
Maybe another hack that could work (in the case of no transparency) would be to draw the fillings one by one on top of each other, but for every *i*-th filling, merge it with all the *j*-th fillings for *j* > *i*, no? I think that's what old MATLAB used to do [(before all the problems it introduced in 2014b)](https://au.mathworks.com/matlabcentral/answers/290313-why-is-vector-graphics-chopped-into-pieces?s_tid=srchtitle), see, e.g., this deconstructed MATLAB `contourf` (from before 2014b, taken from [this post](https://au.mathworks.com/matlabcentral/answers/162257-problem-with-patch-graphics-in-2014b-splits-in-two-along-diagonal)):

<img width=50% src="https://www.mathworks.com/matlabcentral/answers/uploaded_files/174091/image.png">

**Comment by jkrumbiegel** [comment] 2021-02-03 07:19
the problem is that you can't do this in CairoMakie because one poly drawing function doesn't know about others that will happen. You would have to remove the respective holes from the polygons in the contourf function itself, based on the colors given (don't remove when there's transparency)

**Comment by briochemc** [comment] 2021-02-03 09:03
Oh I think you mentioned that previously but I had forgotten about it...

**Comment by jkrumbiegel** [comment] 2021-02-13 17:38
this is fixed now, even though the implementation probably breaks some interactive uses of contourf currently, as a collection of polys in `poly` seems to update incorrectly in glmakie where the `mesh` worked.

**Closed by jkrumbiegel** 2021-02-13 17:38 UTC
