### ISSUE TITLE
Tests for Makie

### ISSUE THREAD

**Issue by mkborregaard** [JuliaPlots/Makie.jl#449] opened 2020-03-12 14:04 UTC
There should be more extensive testing functionality. Like right now MakieThemes is broken and we didn't even notice it.

**Comment by mkborregaard** [comment] 2020-03-12 14:05
Would be cool to have something like the R graph gallery for documentation
https://www.r-graph-gallery.com/

**Comment by asinghvi17** [comment] 2020-03-12 14:09
Would that be an extension of the tag system we have in the Gallery already?

**Comment by SimonDanisch** [comment] 2020-03-12 20:12
Sorry, didn't notice, that this is actually a duplicate of: https://github.com/JuliaPlots/AbstractPlotting.jl/issues/349

**Closed by SimonDanisch** 2020-03-12 20:12 UTC
