### ISSUE TITLE
GLMakie fails to build

### ISSUE THREAD

**Issue by ChetanVardhan** [JuliaPlots/Makie.jl#699] opened 2020-09-09 17:06 UTC
Building GLMakie ─→ `~/.julia/packages/GLMakie/4EXKe/deps/build.log`
┌ Error: Error building `GLMakie`: 
│ libGL error: MESA-LOADER: failed to open iris (search paths /usr/lib64/dri)
│ libGL error: failed to load driver: iris
│ libGL error: MESA-LOADER: failed to open iris (search paths /usr/lib64/dri)
│ libGL error: failed to load driver: iris
│ libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib64/dri)
│ libGL error: failed to load driver: swrast
│ init error of GLFW
│ ERROR: LoadError: OpenGL/GLFW wasn't installed correctly. This likely means,
│ you don't have an OpenGL capable Graphic Card,
│ you don't have the newest video driver installed,
│ or the GLFW build failed. If you're on linux and `]build` GLFW failed,
│ try manually adding `sudo apt-get install libglfw3` and then `]build GLMakie`.
│ If you're on a headless server, you still need to install x-server and
│ proper GPU drivers. You can take inspiration from this article
│ on how to get Makie running on a headless system:
│ https://nextjournal.com/sdanisch/makie-1.0
│ If you don't have a GPU, there is also a Cairo software backend
│ for Makie which you can use:
│ https://github.com/JuliaPlots/CairoMakie.jl.
│ Please check the below error and open an issue at:
│ https://github.com/JuliaPlots/GLMakie.jl.
│ After you fixed your OpenGL install, please run `]build GLMakie` again!
│ GLMakie will still load, but will be disabled as a default backend for Makie
│ 
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] top-level scope at /home/clad/.julia/packages/GLMakie/4EXKe/deps/build.jl:63
│  [3] include(::String) at ./client.jl:457
│  [4] top-level scope at none:5
│ in expression starting at /home/clad/.julia/packages/GLMakie/4EXKe/deps/build.jl:31
│ caused by [exception 1]
│ GLFWError (VERSION_UNAVAILABLE): GLX: Failed to create context: GLXBadFBConfig
│ Stacktrace:
│  [1] _ErrorCallbackWrapper(::Int32, ::Cstring) at /home/clad/.julia/packages/GLFW/CBo9c/src/callback.jl:43
│  [2] CreateWindow(::Int64, ::Int64, ::String, ::GLFW.Monitor, ::GLFW.Window) at /home/clad/.julia/packages/GLFW/CBo9c/src/glfw3.jl:499
│  [3] GLFW.Window(; name::String, resolution::Tuple{Int64,Int64}, debugging::Bool, major::Int64, minor::Int64, windowhints::Array{Tuple{UInt32,Int64},1}, contexthints::Array{Tuple{UInt32,Integer},1}, visible::Bool, focus::Bool, fullscreen::Bool, monitor::Nothing, share::GLFW.Window) at /home/clad/.julia/packages/GLFW/CBo9c/src/glfw3.jl:344
│  [4] top-level scope at /home/clad/.julia/packages/GLMakie/4EXKe/deps/build.jl:34
│  [5] include(::String) at ./client.jl:457
│  [6] top-level scope at none:5
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:949

julia> versioninfo()
Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "/usr/share/code/code"
  JULIA_NUM_THREADS = 
  JULIA_CUDA_USE_BINARYBUILDER = false

ls /usr/lib64/dri/*
/usr/lib64/dri/hybrid_drv_video.so  /usr/lib64/dri/iris_dri.so           /usr/lib64/dri/nouveau_vieux_dri.so  /usr/lib64/dri/r600_dri.so        /usr/lib64/dri/radeonsi_drv_video.so  /usr/lib64/dri/virtio_gpu_dri.so
/usr/lib64/dri/i915_dri.so          /usr/lib64/dri/kms_swrast_dri.so     /usr/lib64/dri/nvidia_drv_video.so   /usr/lib64/dri/r600_drv_video.so  /usr/lib64/dri/s3g_drv_video.so       /usr/lib64/dri/vmwgfx_dri.so
/usr/lib64/dri/i965_dri.so          /usr/lib64/dri/nouveau_dri.so        /usr/lib64/dri/r200_dri.so           /usr/lib64/dri/radeon_dri.so      /usr/lib64/dri/swrast_dri.so
/usr/lib64/dri/i965_drv_video.so    /usr/lib64/dri/nouveau_drv_video.so  /usr/lib64/dri/r300_dri.so           /usr/lib64/dri/radeonsi_dri.so    /usr/lib64/dri/vdpau_drv_video.so

**Comment by SimonDanisch** [comment] 2020-09-09 17:16
Duplicate of: https://github.com/JuliaPlots/Makie.jl/issues/630 & https://github.com/JuliaPlots/Makie.jl/issues/486

**Closed by SimonDanisch** 2020-09-09 17:16 UTC
