### ISSUE TITLE
Partial stroke painting

### ISSUE THREAD

**Issue by Mo8it** [JuliaPlots/Makie.jl#1543] opened 2022-01-06 01:40 UTC
# Problem
The stroke of `poly` is only partially painted. See example below.

# Input
```julia
julia> using GLMakie

julia> poly(Circle(Point(0.0, 0.0), 1), strokecolor=RGBAf(1.0, 0.0, 0.0, 1.0), strokewidth=5, color=RGBAf(0.0, 0.0, 0.0, 0.0))
```

# Output
![image](https://user-images.githubusercontent.com/76752051/148313906-b2307028-ca54-4076-b60c-f41358a41908.png)

# Expected
Circle as stroke.

# Version
```julia
julia> versioninfo()
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: AMD Ryzen 7 5800H with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, znver3)
Environment:
  JULIA_NUM_THREADS = 16
```

GLMakie v0.4.7
Makie v0.15.3

**Comment by SimonDanisch** [comment] 2022-01-06 11:00
Ugh, cant replicate this on master/tagged :(  So, I guess this is a duplicate of: 
https://github.com/JuliaPlots/Makie.jl/issues/1460

**Closed by SimonDanisch** 2022-01-06 11:00 UTC
