### ISSUE TITLE
Linspace is not working

### ISSUE THREAD

**Issue by Salehman** [JuliaPlots/Makie.jl#193] opened 2018-10-26 03:21 UTC
I have read that linspace is no longer a function in Julia. Maybe it is a good idea if all linspace functions in the examples are changed to range.

**Comment by SimonDanisch** [comment] 2018-10-26 09:35
duplicate of https://github.com/JuliaPlots/Makie.jl/issues/148

**Closed by SimonDanisch** 2018-10-26 09:35 UTC
