### ISSUE TITLE
Environment broken

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [JuliaPlots/Makie.jl#1091] opened 2021-07-02 03:31 UTC
When I run :

```julia
using GLMakie
x = LinRange(0, 10, 100)
y = sin.(x)
lines(x, y)
```

I got errors:

```julia
ERROR: type GridLayout has no field needs_update
Stacktrace:
  [1] getproperty(x::GridLayout, f::Symbol)
    @ Base ./Base.jl:33
  [2] (::AbstractPlotting.var"#831#832"{GridLayout})(al::Outside)
    @ AbstractPlotting ~/.julia/packages/AbstractPlotting/M8Nlv/src/figures.jl:80
  [3] #invokelatest#2
    @ ./essentials.jl:708 [inlined]
  [4] invokelatest
    @ ./essentials.jl:706 [inlined]
  [5] setindex!(observable::Observable{Outside}, val::Outside; notify::Observables.var"#9#11")
    @ Observables ~/.julia/packages/Observables/Yf3xU/src/Observables.jl:207
  [6] setindex!
    @ ~/.julia/packages/Observables/Yf3xU/src/Observables.jl:201 [inlined]
  [7] notify!
    @ ~/.julia/packages/Observables/Yf3xU/src/Observables.jl:72 [inlined]
  [8] notify
    @ ~/.julia/packages/AbstractPlotting/M8Nlv/src/AbstractPlotting.jl:35 [inlined]
  [9] Figure(; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ AbstractPlotting ~/.julia/packages/AbstractPlotting/M8Nlv/src/figures.jl:82
 [10] Figure
    @ ~/.julia/packages/AbstractPlotting/M8Nlv/src/figures.jl:67 [inlined]
 [11] plot(::Type{Lines{ArgType} where ArgType}, ::LinRange{Float64}, ::Vararg{Any, N} where N; axis::NamedTuple{(), Tuple{}}, figure::NamedTuple{(), Tuple{}}, kw_attributes::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ AbstractPlotting ~/.julia/packages/AbstractPlotting/M8Nlv/src/figureplotting.jl:18
 [12] plot(::Type{Lines{ArgType} where ArgType}, ::LinRange{Float64}, ::Vector{Float64})
    @ AbstractPlotting ~/.julia/packages/AbstractPlotting/M8Nlv/src/figureplotting.jl:18
 [13] lines(::LinRange{Float64}, ::Vararg{Any, N} where N; attributes::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ AbstractPlotting ~/.julia/packages/AbstractPlotting/M8Nlv/src/recipes.jl:12
 [14] lines(::LinRange{Float64}, ::Vararg{Any, N} where N)
    @ AbstractPlotting ~/.julia/packages/AbstractPlotting/M8Nlv/src/recipes.jl:12
 [15] top-level scope
    @ REPL[4]:1
```

code below came to the same errors
```julia
x = LinRange(0, 10, 100)
y = sin.(x)
scatter(x, y)
```

Basic plotting functions failed. And I had updated and built my environment with PKG with no errors.

**Comment by Xinyu-Wu-0000** [comment] 2021-07-02 05:24
When I run `test GLMakie`

```julia
Testing Running tests...
┌ Warning: _findmod is deprecated and will be removed. Use `Base.require(::Base.PkgId)` instead.
│   caller = (::ImageIO.var"#1#2"{Symbol})() at ImageIO.jl:17
└ @ ImageIO ~/.julia/packages/ImageIO/uPn5K/src/ImageIO.jl:17
Window handling: Error During Test at /home/wuxinyu/.julia/packages/GLMakie/rcykA/test/unit_tests.jl:10
  Got exception outside of a @test
  type GridLayout has no field needs_update
  Stacktrace:
    [1] getproperty(x::GridLayout, f::Symbol)
      @ Base ./Base.jl:33
    [2] (::AbstractPlotting.var"#831#832"{GridLayout})(al::Outside)
      @ AbstractPlotting ~/.julia/packages/AbstractPlotting/M8Nlv/src/figures.jl:80
    [3] #invokelatest#2
      @ ./essentials.jl:708 [inlined]
    [4] invokelatest
      @ ./essentials.jl:706 [inlined]
    [5] setindex!(observable::Observable{Outside}, val::Outside; notify::Observables.var"#9#11")
      @ Observables ~/.julia/packages/Observables/Yf3xU/src/Observables.jl:207
    [6] setindex!
      @ ~/.julia/packages/Observables/Yf3xU/src/Observables.jl:201 [inlined]
    [7] notify!
      @ ~/.julia/packages/Observables/Yf3xU/src/Observables.jl:72 [inlined]
    [8] notify
      @ ~/.julia/packages/AbstractPlotting/M8Nlv/src/AbstractPlotting.jl:35 [inlined]
    [9] Figure(; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ AbstractPlotting ~/.julia/packages/AbstractPlotting/M8Nlv/src/figures.jl:82
   [10] Figure
      @ ~/.julia/packages/AbstractPlotting/M8Nlv/src/figures.jl:67 [inlined]
   [11] plot(P::Type{Scatter{ArgType} where ArgType}, args::UnitRange{Int64}; axis::NamedTuple{(), Tuple{}}, figure::NamedTuple{(), Tuple{}}, kw_attributes::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ AbstractPlotting ~/.julia/packages/AbstractPlotting/M8Nlv/src/figureplotting.jl:18
   [12] plot
      @ ~/.julia/packages/AbstractPlotting/M8Nlv/src/figureplotting.jl:18 [inlined]
   [13] #scatter#151
      @ ~/.julia/packages/AbstractPlotting/M8Nlv/src/recipes.jl:12 [inlined]
   [14] scatter(args::UnitRange{Int64})
      @ AbstractPlotting ~/.julia/packages/AbstractPlotting/M8Nlv/src/recipes.jl:12
   [15] macro expansion
      @ ~/.julia/packages/GLMakie/rcykA/test/unit_tests.jl:14 [inlined]
   [16] macro expansion
      @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
   [17] macro expansion
      @ ~/.julia/packages/GLMakie/rcykA/test/unit_tests.jl:11 [inlined]
   [18] macro expansion
      @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
   [19] top-level scope
      @ ~/.julia/packages/GLMakie/rcykA/test/unit_tests.jl:10
   [20] include(fname::String)
      @ Base.MainInclude ./client.jl:444
   [21] top-level scope
      @ ~/.julia/packages/GLMakie/rcykA/test/runtests.jl:14
   [22] include(fname::String)
      @ Base.MainInclude ./client.jl:444
   [23] top-level scope
      @ none:6
   [24] eval
      @ ./boot.jl:360 [inlined]
   [25] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:261
   [26] _start()
      @ Base ./client.jl:485
Pick a plot element or plot elements inside a rectangle: Error During Test at /home/wuxinyu/.julia/packages/GLMakie/rcykA/test/unit_tests.jl:27
  Got exception outside of a @test
  type GridLayout has no field needs_update
  Stacktrace:
    [1] getproperty(x::GridLayout, f::Symbol)
      @ Base ./Base.jl:33
    [2] (::AbstractPlotting.var"#831#832"{GridLayout})(al::Outside)
      @ AbstractPlotting ~/.julia/packages/AbstractPlotting/M8Nlv/src/figures.jl:80
    [3] #invokelatest#2
      @ ./essentials.jl:708 [inlined]
    [4] invokelatest
      @ ./essentials.jl:706 [inlined]
    [5] setindex!(observable::Observable{Outside}, val::Outside; notify::Observables.var"#9#11")
      @ Observables ~/.julia/packages/Observables/Yf3xU/src/Observables.jl:207
    [6] setindex!
      @ ~/.julia/packages/Observables/Yf3xU/src/Observables.jl:201 [inlined]
    [7] notify!
      @ ~/.julia/packages/Observables/Yf3xU/src/Observables.jl:72 [inlined]
    [8] notify
      @ ~/.julia/packages/AbstractPlotting/M8Nlv/src/AbstractPlotting.jl:35 [inlined]
    [9] Figure(; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ AbstractPlotting ~/.julia/packages/AbstractPlotting/M8Nlv/src/figures.jl:82
   [10] Figure
      @ ~/.julia/packages/AbstractPlotting/M8Nlv/src/figures.jl:67 [inlined]
   [11] plot(::Type{Scatter{ArgType} where ArgType}, ::UnitRange{Int64}, ::Vararg{UnitRange{Int64}, N} where N; axis::NamedTuple{(), Tuple{}}, figure::NamedTuple{(), Tuple{}}, kw_attributes::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ AbstractPlotting ~/.julia/packages/AbstractPlotting/M8Nlv/src/figureplotting.jl:18
   [12] plot(::Type{Scatter{ArgType} where ArgType}, ::UnitRange{Int64}, ::UnitRange{Int64})
      @ AbstractPlotting ~/.julia/packages/AbstractPlotting/M8Nlv/src/figureplotting.jl:18
   [13] scatter(::UnitRange{Int64}, ::Vararg{UnitRange{Int64}, N} where N; attributes::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ AbstractPlotting ~/.julia/packages/AbstractPlotting/M8Nlv/src/recipes.jl:12
   [14] scatter(::UnitRange{Int64}, ::Vararg{UnitRange{Int64}, N} where N)
      @ AbstractPlotting ~/.julia/packages/AbstractPlotting/M8Nlv/src/recipes.jl:12
   [15] macro expansion
      @ ~/.julia/packages/GLMakie/rcykA/test/unit_tests.jl:29 [inlined]
   [16] macro expansion
      @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
   [17] macro expansion
      @ ~/.julia/packages/GLMakie/rcykA/test/unit_tests.jl:28 [inlined]
   [18] macro expansion
      @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
   [19] top-level scope
      @ ~/.julia/packages/GLMakie/rcykA/test/unit_tests.jl:10
   [20] include(fname::String)
      @ Base.MainInclude ./client.jl:444
   [21] top-level scope
      @ ~/.julia/packages/GLMakie/rcykA/test/runtests.jl:14
   [22] include(fname::String)
      @ Base.MainInclude ./client.jl:444
   [23] top-level scope
      @ none:6
   [24] eval
      @ ./boot.jl:360 [inlined]
   [25] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:261
   [26] _start()
      @ Base ./client.jl:485
Test Summary:                                             | Pass  Error  Total
unit tests                                                |    1      2      3
  Window handling                                         |    1      1      2
  Pick a plot element or plot elements inside a rectangle |           1      1
ERROR: LoadError: LoadError: Some tests did not pass: 1 passed, 0 failed, 2 errored, 0 broken.
in expression starting at /home/wuxinyu/.julia/packages/GLMakie/rcykA/test/unit_tests.jl:9
in expression starting at /home/wuxinyu/.julia/packages/GLMakie/rcykA/test/runtests.jl:14
ERROR: Package GLMakie errored during testing
```

**Comment by jkrumbiegel** [comment] 2021-07-02 05:28
You can either pin GridLayoutBase to version 0.5.4 or update Makie, this is a regression because an internal implementation was changed that happened to be used in Makie after all.

**Comment by Xinyu-Wu-0000** [comment] 2021-07-02 15:52
> You can either pin GridLayoutBase to version 0.5.4 or update Makie, this is a regression because an internal implementation was changed that happened to be used in Makie after all.

But when I used Pkg.update() or Pkg.update("Makie"), Makie stayed at version v0.13.14.

**Comment by jkrumbiegel** [comment] 2021-07-02 16:44
Try updating again, I just pushed a fix to GridLayoutBase which should be pulled in, makie can stay the same

**Closed** 2021-07-02 16:45 UTC
