### ISSUE TITLE
test errors

### ISSUE THREAD

**Issue by AshtonSBradley** [JuliaPlots/Makie.jl#68] opened 2018-02-10 09:51 UTC
`Pkg.test("Makie") gives several erros. The last one is 
```julia
testfunc_13: jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:592
jl_parse_eval_all at /Users/osx/buildbot/slave/package_osx64/build/src/ast.c:873
jl_load at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:616 [inlined]
jl_load_ at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:623
include_from_node1 at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jlcall_include_from_node1_18705 at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
include at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jlcall_include_1022 at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
process_options at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
_start at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jlcall__start_18944 at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
true_main at /Applications/Julia-0.6.app/Contents/Resources/julia/bin/julia (unknown line)
main at /Applications/Julia-0.6.app/Contents/Resources/julia/bin/julia (unknown line)
unknown function (ip: 0xffffffffffffffff)
Allocations: 78931682 (Pool: 78924195; Big: 7487); GC: 211
========================================[ ERROR: Makie ]========================================

failed process: Process(`/Applications/Julia-0.6.app/Contents/Resources/julia/bin/julia -Cnative -J/Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes /Users/abradley/.julia/v0.6/Makie/test/runtests.jl`, ProcessExited(130)) [130]

================================================================================================
INFO: Removing Matcha v0.1.1
ERROR: Makie had test errors
```

```julia
julia> versioninfo()
Julia Version 0.6.2
Commit d386e40c17 (2017-12-13 18:08 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```

**Comment by SimonDanisch** [comment] 2018-02-10 10:10
Would be nice if you don't truncate error logs! ;) I almost always need to see the whole thing, even if it's just to make sure, that it's not a previous warning/error.
Hopefully this one is related to previous errors, since on it's own, this segfault isn't very informative :(

**Comment by AshtonSBradley** [comment] 2018-02-11 01:17
sorry about that, here's the whole log:
```julia
julia> Pkg.test("Makie")
INFO: Computing test dependencies for Makie...
INFO: No packages to install, update or remove
INFO: Testing Makie
ERROR (unhandled task failure): AssertionError: g_stack !== nothing && (g_stack != ct && !prev)
Stacktrace:
 [1] g_sigatom(::Any) at /Users/abradley/.julia/v0.6/Gtk/src/GLib/signals.jl:151
 [2] gtk_main() at /Users/abradley/.julia/v0.6/Gtk/src/events.jl:1
Scene scene:
Dict{Symbol,Any} with 24 entries:
  :screen => name: Makie
children: 0
Inputs:
  mouse_button_released => Reactive.Signal{Int64}
  mouse_buttons_pressed => Reactive.Signal{Set{Int64}}
  scroll => Reactive.Signal{GeometryTypes.Vec{2,Float64}}
  buttons_pressed => Reactive.Signal{Set{Int64}}
  window_size => Reactive.Signal{GeometryTypes.Vec{2,Int64}}
  window_area => Reactive.Signal{GeometryTypes.SimpleRectangle{Int64}}
  cursor_position => Reactive.Signal{GeometryTypes.Vec{2,Float64}}
  mouseinside => Reactive.Signal{Bool}
  mouse_button_down => Reactive.Signal{Int64}
  mouseposition => Reactive.Signal{GeometryTypes.Vec{2,Float64}}
  arrow_navigation => Reactive.Signal{Symbol}
  key_pressed => Reactive.Signal{Bool}
  mouse2id => Reactive.Signal{GLWindow.SelectionID{Int64}}
  framebuffer_size => Reactive.Signal{GeometryTypes.Vec{2,Int64}}
  button_down => Reactive.Signal{Int64}
  unicode_input => Reactive.Signal{Array{Char,1}}
  window_position => Reactive.Signal{GeometryTypes.Vec{2,Int64}}
  mouse_buttons => Reactive.Signal{Tuple{Int64,Int64,Int64}}
  entered_window => Reactive.Signal{Bool}
  button_released => Reactive.Signal{Int64}
  window_open => Reactive.Signal{Bool}
  dropped_files => Reactive.Signal{Array{String,1}}
  hasfocus => Reactive.Signal{Bool}
  keyboard_buttons => Reactive.Signal{NTuple{4,Int64}}

  :mouse_button_released => <Node: 0>
  :mouse_buttons_pressed => <Node: Set{Int64}()>
  :time => <Node: 1.51831e9>
  :scroll => <Node: [0.0, 0.0]>
  :buttons_pressed => <Node: Set{Int64}()>
  :window_area => <Node: GeometryTypes.SimpleRectangle{Int64}(0, 0, 500, 500)>
  :theme => Scene: scene
  :mouseinside => <Node: true>
  :mouse_button_down => <Node: 0>
  :mouseposition => <Node: [0.0, 500.0]>
  :arrow_navigation => <Node: :nothing>
  :key_pressed => <Node: false>
  :mouse2id => <Node: [-1, -1]>
  :button_down => <Node: 0>
  :unicode_input => <Node: Char[]>
  :window_position => <Node: [0, 0]>
  :mouse_buttons => <Node: (0, 0, 0)>
  :entered_window => <Node: false>
  :button_released => <Node: 0>
  :window_open => <Node: true>
  :dropped_files => <Node: String[]>
  :hasfocus => <Node: false>
  :keyboard_buttons => <Node: (0, 0, 0, 0)>Scene: sceneScene: scene
INFO: Reference image /Users/abradley/.julia/v0.6/ReferenceImages/reference_images/img_1.png matches.  Difference: 0.00020713700244291358
WARNING: takebuf_string(b) is deprecated, use String(take!(b)) instead.
Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:70
 [2] takebuf_string(::Base.AbstractIOBuffer{Array{UInt8,1}}) at ./deprecated.jl:57
 [3] to_latex(::String) at /Users/abradley/.julia/v0.6/UnicodeFun/src/latex.jl:82
 [4] draw_axis(::Makie.TextBuffer{3}, ::Makie.LinesegmentBuffer{3}, ::Tuple{StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}, ::Tuple{String,String,String}, ::Tuple{ColorTypes.RGBA{Float32},ColorTypes.RGBA{Float32},ColorTypes.RGBA{Float32}}, ::Tuple{Float32,Float32,Float32}, ::Tuple{Tuple{GeometryTypes.Vec{4,Float32},Tuple{Symbol,Symbol}},Tuple{GeometryTypes.Vec{4,Float32},Tuple{Symbol,Symbol}},Tuple{GeometryTypes.Vec{4,Float32},Tuple{Symbol,Symbol}}}, ::Array{Ptr{FreeType.FT_FaceRec},1}, ::Bool, ::Tuple{Bool,Bool,Bool}, ::Tuple{Bool,Bool,Bool}, ::Tuple{Bool,Bool,Bool}, ::Tuple{ColorTypes.RGBA{Float32},ColorTypes.RGBA{Float32},ColorTypes.RGBA{Float32}}, ::Tuple{ColorTypes.RGBA{Float32},ColorTypes.RGBA{Float32},ColorTypes.RGBA{Float32}}, ::Tuple{Float32,Float32,Float32}, ::Tuple{Tuple{Float64,ColorTypes.RGBA{Float32},GeometryTypes.Vec{4,Float32},Tuple{Symbol,Symbol}},Tuple{Float64,ColorTypes.RGBA{Float32},GeometryTypes.Vec{4,Float32},Tuple{Symbol,Symbol}},Tuple{Float64,ColorTypes.RGBA{Float32},GeometryTypes.Vec{4,Float32},Tuple{Symbol,Symbol}}}) at /Users/abradley/.julia/v0.6/Makie/src/plotsbase/axis.jl:57
 [5] map(::Function, ::Reactive.Signal{Makie.TextBuffer{3}}, ::Reactive.Signal{Makie.LinesegmentBuffer{3}}, ::Reactive.Signal{Tuple{StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}}, ::Vararg{Reactive.Signal,N} where N) at /Users/abradley/.julia/v0.6/Reactive/src/operators.jl:32
 [6] #foreach#37(::Array{Any,1}, ::Function, ::Function, ::Reactive.Signal{Makie.TextBuffer{3}}, ::Reactive.Signal{Makie.LinesegmentBuffer{3}}, ::Vararg{Reactive.Signal,N} where N) at /Users/abradley/.julia/v0.6/Reactive/src/operators.jl:51
 [7] foreach(::Function, ::Reactive.Signal{Makie.TextBuffer{3}}, ::Reactive.Signal{Makie.LinesegmentBuffer{3}}, ::Vararg{Reactive.Signal,N} where N) at /Users/abradley/.julia/v0.6/Reactive/src/operators.jl:51
 [8] lift_node(::Function, ::Makie.Node{Makie.TextBuffer{3},Base.#identity}, ::Makie.Node{Makie.LinesegmentBuffer{3},Base.#identity}, ::Vararg{Union{Makie.ArrayNode{T,N,F,AT} where AT<:AbstractArray where F where N, Makie.Node{T,F} where F} where T,N} where N) at /Users/abradley/.julia/v0.6/Makie/src/plotsbase/signals.jl:61
 [9] axis(::Makie.Scene{:makie}, ::Makie.Node{Tuple{StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}},Base.#identity}, ::Dict{Symbol,Any}) at /Users/abradley/.julia/v0.6/Makie/src/plotsbase/axis.jl:101
 [10] axis(::Makie.Scene{:makie}, ::StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}, ::StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}, ::StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}) at /Users/abradley/.julia/v0.6/Makie/src/plotsbase/atomics.jl:357
 [11] #axis#490(::Array{Any,1}, ::Function, ::StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}, ::StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}, ::Vararg{StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},N} where N) at /Users/abradley/.julia/v0.6/Makie/src/plotsbase/atomics.jl:348
 [12] testfunc_2() at /Users/abradley/.julia/v0.6/Makie/test/visual_regression_funcs.jl:60
 [13] record(::String, ::#testfunc_2) at /Users/abradley/.julia/v0.6/Makie/test/visual_regression.jl:19
 [14] (::#f#74)(::String) at /Users/abradley/.julia/v0.6/Makie/test/visual_regression.jl:45
 [15] #test_images#7(::Bool, ::Array{Any,1}, ::Function, ::VisualRegressionTests.VisualTest) at /Users/abradley/.julia/v0.6/VisualRegressionTests/src/imgcomp.jl:79
 [16] (::VisualRegressionTests.#kw##test_images)(::Array{Any,1}, ::VisualRegressionTests.#test_images, ::VisualRegressionTests.VisualTest) at ./<missing>:0
 [17] macro expansion at /Users/abradley/.julia/v0.6/Makie/test/visual_regression.jl:47 [inlined]
 [18] macro expansion at ./test.jl:860 [inlined]
 [19] macro expansion at /Users/abradley/.julia/v0.6/Makie/test/visual_regression.jl:46 [inlined]
 [20] macro expansion at ./test.jl:860 [inlined]
 [21] anonymous at ./<missing>:?
 [22] include_from_node1(::String) at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 [23] include(::String) at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 [24] include_from_node1(::String) at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 [25] include(::String) at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 [26] process_options(::Base.JLOptions) at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 [27] _start() at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/abradley/.julia/v0.6/Makie/test/visual_regression.jl, in expression starting on line 37
WARNING: Got error: ErrorException("Arrays differ.  Difference: 0.024418651800315647  eps: 0.02")
WARNING: Image did not match reference image /Users/abradley/.julia/v0.6/ReferenceImages/reference_images/img_2.png. err: ErrorException("Arrays differ.  Difference: 0.024418651800315647  eps: 0.02")
testfunc_2: Test Failed
  Expression: test_images(VisualTest(f, path), popup=false) |> success
Stacktrace:
 [1] macro expansion at /Users/abradley/.julia/v0.6/Makie/test/visual_regression.jl:47 [inlined]
 [2] macro expansion at ./test.jl:860 [inlined]
 [3] macro expansion at /Users/abradley/.julia/v0.6/Makie/test/visual_regression.jl:46 [inlined]
 [4] macro expansion at ./test.jl:860 [inlined]
 [5] anonymous at ./<missing>:?
WARNING: Got error: ErrorException("Arrays differ.  Difference: 0.024907526838432004  eps: 0.02")
WARNING: Image did not match reference image /Users/abradley/.julia/v0.6/ReferenceImages/reference_images/img_3.png. err: ErrorException("Arrays differ.  Difference: 0.024907526838432004  eps: 0.02")
testfunc_3: Test Failed
  Expression: test_images(VisualTest(f, path), popup=false) |> success
Stacktrace:
 [1] macro expansion at /Users/abradley/.julia/v0.6/Makie/test/visual_regression.jl:47 [inlined]
 [2] macro expansion at ./test.jl:860 [inlined]
 [3] macro expansion at /Users/abradley/.julia/v0.6/Makie/test/visual_regression.jl:46 [inlined]
 [4] macro expansion at ./test.jl:860 [inlined]
 [5] anonymous at ./<missing>:?
INFO: Reference image /Users/abradley/.julia/v0.6/ReferenceImages/reference_images/img_4.png matches.  Difference: 0.0011256358409931315
INFO: Reference image /Users/abradley/.julia/v0.6/ReferenceImages/reference_images/img_5.png matches.  Difference: 3.1918840806629706e-5
INFO: Reference image /Users/abradley/.julia/v0.6/ReferenceImages/reference_images/img_6.png matches.  Difference: 0.0002829123938849179
INFO: Reference image /Users/abradley/.julia/v0.6/ReferenceImages/reference_images/img_7.png matches.  Difference: 2.6113764607626236e-5
WARNING: Got error: ErrorException("Arrays differ.  Difference: 0.05298791671265425  eps: 0.02")
WARNING: Image did not match reference image /Users/abradley/.julia/v0.6/ReferenceImages/reference_images/img_8.png. err: ErrorException("Arrays differ.  Difference: 0.05298791671265425  eps: 0.02")
testfunc_8: Test Failed
  Expression: test_images(VisualTest(f, path), popup=false) |> success
Stacktrace:
 [1] macro expansion at /Users/abradley/.julia/v0.6/Makie/test/visual_regression.jl:47 [inlined]
 [2] macro expansion at ./test.jl:860 [inlined]
 [3] macro expansion at /Users/abradley/.julia/v0.6/Makie/test/visual_regression.jl:46 [inlined]
 [4] macro expansion at ./test.jl:860 [inlined]
 [5] anonymous at ./<missing>:?
INFO: Reference image /Users/abradley/.julia/v0.6/ReferenceImages/reference_images/img_9.png matches.  Difference: 0.00017676958955272995
WARNING: Got error: ErrorException("Arrays differ.  Difference: 0.05525582986998196  eps: 0.02")
WARNING: Image did not match reference image /Users/abradley/.julia/v0.6/ReferenceImages/reference_images/img_10.png. err: ErrorException("Arrays differ.  Difference: 0.05525582986998196  eps: 0.02")
testfunc_10: Test Failed
  Expression: test_images(VisualTest(f, path), popup=false) |> success
Stacktrace:
 [1] macro expansion at /Users/abradley/.julia/v0.6/Makie/test/visual_regression.jl:47 [inlined]
 [2] macro expansion at ./test.jl:860 [inlined]
 [3] macro expansion at /Users/abradley/.julia/v0.6/Makie/test/visual_regression.jl:46 [inlined]
 [4] macro expansion at ./test.jl:860 [inlined]
 [5] anonymous at ./<missing>:?
WARNING: Got error: ErrorException("Arrays differ.  Difference: 0.07389470736534379  eps: 0.02")
WARNING: Image did not match reference image /Users/abradley/.julia/v0.6/ReferenceImages/reference_images/img_11.png. err: ErrorException("Arrays differ.  Difference: 0.07389470736534379  eps: 0.02")
testfunc_11: Test Failed
  Expression: test_images(VisualTest(f, path), popup=false) |> success
Stacktrace:
 [1] macro expansion at /Users/abradley/.julia/v0.6/Makie/test/visual_regression.jl:47 [inlined]
 [2] macro expansion at ./test.jl:860 [inlined]
 [3] macro expansion at /Users/abradley/.julia/v0.6/Makie/test/visual_regression.jl:46 [inlined]
 [4] macro expansion at ./test.jl:860 [inlined]
 [5] anonymous at ./<missing>:?
WARNING: Got error: ErrorException("Arrays differ.  Difference: 0.18360049479543378  eps: 0.02")
WARNING: Image did not match reference image /Users/abradley/.julia/v0.6/ReferenceImages/reference_images/img_12.png. err: ErrorException("Arrays differ.  Difference: 0.18360049479543378  eps: 0.02")
testfunc_12: Test Failed
  Expression: test_images(VisualTest(f, path), popup=false) |> success
Stacktrace:
 [1] macro expansion at /Users/abradley/.julia/v0.6/Makie/test/visual_regression.jl:47 [inlined]
 [2] macro expansion at ./test.jl:860 [inlined]
 [3] macro expansion at /Users/abradley/.julia/v0.6/Makie/test/visual_regression.jl:46 [inlined]
 [4] macro expansion at ./test.jl:860 [inlined]
 [5] anonymous at ./<missing>:?

signal (2): Interrupt: 2
while loading /Users/abradley/.julia/v0.6/Makie/test/visual_regression.jl, in expression starting on line 37
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
__psynch_cvwait at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
jl_typemap_assoc_exact at /Users/osx/buildbot/slave/package_osx64/build/src/./julia_internal.h:892 [inlined]
jl_lookup_generic_ at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1871
jl_apply_generic at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1923
Type at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jlcall_Type_455 at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
Type at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
typeinf_frame at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
typeinf_code at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jlcall_typeinf_code_950 at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
typeinf_ext at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jlcall_typeinf_ext_0 at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply at /Users/osx/buildbot/slave/package_osx64/build/src/./julia.h:1424 [inlined]
jl_apply_with_saved_exception_state at /Users/osx/buildbot/slave/package_osx64/build/src/rtutils.c:257
jl_type_infer at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:262
jl_compile_for_dispatch at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1661
jl_compile_method_internal at /Users/osx/buildbot/slave/package_osx64/build/src/./julia_internal.h:307 [inlined]
jl_call_method_internal at /Users/osx/buildbot/slave/package_osx64/build/src/./julia_internal.h:354 [inlined]
jl_apply_generic at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1926
_jl_spawn at ./process.jl:360
unknown function (ip: 0x135dbb0ae)
#374 at ./process.jl:512 [inlined]
setup_stdio at ./process.jl:499
#spawn#373 at ./process.jl:511
unknown function (ip: 0x135db9fa2)
spawn at ./process.jl:506
unknown function (ip: 0x135db9c06)
open at ./process.jl:583
Type at /Users/abradley/.julia/v0.6/Makie/src/plotsbase/output.jl:79
Type at /Users/abradley/.julia/v0.6/Makie/src/plotsbase/output.jl:72
testfunc_13 at /Users/abradley/.julia/v0.6/Makie/test/visual_regression_funcs.jl:256
record at /Users/abradley/.julia/v0.6/Makie/test/visual_regression.jl:19
unknown function (ip: 0x135da7a52)
f at /Users/abradley/.julia/v0.6/Makie/test/visual_regression.jl:45
jl_apply at /Users/osx/buildbot/slave/package_osx64/build/src/./julia.h:1424 [inlined]
jl_f__apply at /Users/osx/buildbot/slave/package_osx64/build/src/builtins.c:426
#test_images#7 at /Users/abradley/.julia/v0.6/VisualRegressionTests/src/imgcomp.jl:79
unknown function (ip: 0x1216894b5)
#test_images at ./<missing>:0
macro expansion at /Users/abradley/.julia/v0.6/Makie/test/visual_regression.jl:47 [inlined]
macro expansion at ./test.jl:860 [inlined]
macro expansion at /Users/abradley/.julia/v0.6/Makie/test/visual_regression.jl:46 [inlined]
macro expansion at ./test.jl:860 [inlined]
anonymous at ./<missing> (unknown line)
jl_call_fptr_internal at /Users/osx/buildbot/slave/package_osx64/build/src/./julia_internal.h:339 [inlined]
jl_call_method_internal at /Users/osx/buildbot/slave/package_osx64/build/src/./julia_internal.h:358 [inlined]
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:589
jl_parse_eval_all at /Users/osx/buildbot/slave/package_osx64/build/src/ast.c:873
jl_load at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:616 [inlined]
jl_load_ at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:623
include_from_node1 at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jlcall_include_from_node1_18705 at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
include at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jlcall_include_1022 at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
do_call at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:75
eval at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:242
eval_body at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:543
jl_interpret_toplevel_thunk at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:692
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:592
jl_parse_eval_all at /Users/osx/buildbot/slave/package_osx64/build/src/ast.c:873
jl_load at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:616 [inlined]
jl_load_ at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:623
include_from_node1 at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jlcall_include_from_node1_18705 at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
include at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jlcall_include_1022 at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
process_options at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
_start at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jlcall__start_18944 at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
true_main at /Applications/Julia-0.6.app/Contents/Resources/julia/bin/julia (unknown line)
main at /Applications/Julia-0.6.app/Contents/Resources/julia/bin/julia (unknown line)
unknown function (ip: 0xffffffffffffffff)
Allocations: 78533195 (Pool: 78525861; Big: 7334); GC: 210
LLVM ERROR: Starting a frame before finishing the previous one!
================================[ ERROR: Makie ]================================

failed process: Process(`/Applications/Julia-0.6.app/Contents/Resources/julia/bin/julia -Cnative -J/Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes /Users/abradley/.julia/v0.6/Makie/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
INFO: No packages to install, update or remove
ERROR: Makie had test errors
```

**Comment by AshtonSBradley** [comment] 2018-03-05 04:00
So the tests all "fail", but each one still generates graphical output that looks sensible.  Doesn't happen on my laptop, just on the desktop.

**Comment by SimonDanisch** [comment] 2018-03-06 09:30
I just pushed a fix for that, can you try again?

**Comment by SimonDanisch** [comment] 2018-03-06 09:31
Around 18 visual regression are expected to fail on current master ;)

**Comment by SimonDanisch** [comment] 2018-03-06 09:32
So if the above log has the `signal (2): Interrupt: 2` from you force exiting julia, all should be good! Please open a new issue if there are still problems :)

**Closed by SimonDanisch** 2018-03-06 09:32 UTC
