### ISSUE TITLE
Failed to precompile GLMakie: to_gl_text not defined

### ISSUE THREAD

**Issue by gszep** [JuliaPlots/Makie.jl#873] opened 2021-03-11 07:46 UTC
Ubuntu 18.04 | OpenGL version: 4.6.0 NVIDIA 460.32.03
```julia
pkg> st
Status `~/.julia/pluto_notebooks/Project.toml`
  [537997a7] AbstractPlotting v0.15.24
  [e9467ef8] GLMakie v0.1.29

julia> using AbstractPlotting
[ Info: Precompiling AbstractPlotting [537997a7-5e4e-5d89-9595-2241ea00577e]

julia> using GLMakie
[ Info: Precompiling GLMakie [e9467ef8-e4e7-5192-8a1a-b1aee30e663a]
ERROR: LoadError: UndefVarError: to_gl_text not defined
Stacktrace:
 [1] _precompile_() at /home/gszep/.julia/packages/GLMakie/AiucZ/src/precompile.jl:9
 [2] top-level scope at /home/gszep/.julia/packages/GLMakie/AiucZ/src/GLMakie.jl:82
 [3] include(::Function, ::Module, ::String) at ./Base.jl:380
 [4] include(::Module, ::String) at ./Base.jl:368
 [5] top-level scope at none:2
 [6] eval at ./boot.jl:331 [inlined]
 [7] eval(::Expr) at ./client.jl:467
 [8] top-level scope at ./none:3
in expression starting at /home/gszep/.julia/packages/GLMakie/AiucZ/src/GLMakie.jl:80
ERROR: Failed to precompile GLMakie [e9467ef8-e4e7-5192-8a1a-b1aee30e663a] to /home/gszep/.julia/compiled/v1.5/GLMakie/nfnZR_J18Ed.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1305
 [3] _require(::Base.PkgId) at ./loading.jl:1030
 [4] require(::Base.PkgId) at ./loading.jl:928
 [5] require(::Module, ::Symbol) at ./loading.jl:923
```
Probably related to #712 and https://github.com/JuliaGL/GLFW.jl/issues/198. `libglfw3` is installed and passes the `glmark2` benchmark. Fixed the julia problem by removing `libstdc++` and rebuilding GLMakie. It appears not to be necessary to create a symbolic link to the system library living at `/usr/lib/x86_64-linux-gnu/libstdc++.so.6`
```bash
rm <julia-install-path>/lib/julia/libstdc++.so.6
```
```julia
pkg> build GLMakie
   Building ModernGL → `~/.julia/packages/ModernGL/rVuW2/deps/build.log`
   Building FFTW ────→ `~/.julia/packages/FFTW/G3lSO/deps/build.log`
   Building GLMakie ─→ `~/.julia/packages/GLMakie/AiucZ/deps/build.log`

julia> using GLMakie
[ Info: Precompiling GLMakie [e9467ef8-e4e7-5192-8a1a-b1aee30e663a]
```

**Comment by ffreyer** [comment] 2021-03-11 11:20
Duplicate of #846 and #843 though neither of them have been solved.

**Comment by SimonDanisch** [comment] 2021-03-11 11:27
Oooh, I think I finally understand this issue...
When `WORKING_OPENGL` is false, additional imports aren't loaded:
https://github.com/JuliaPlots/GLMakie.jl/blob/master/src/GLMakie.jl#L56
So then it will fail in the precompile step...
We need to clean up this whole conditional loading and checking for a working OpenGL

**Closed** 2021-03-16 17:49 UTC

**Comment by zzheng93** [comment] 2021-03-16 21:05
Hi @SimonDanisch , could you please let me know the solution?

**Comment by SimonDanisch** [comment] 2021-03-16 21:29
Update to this new version: https://github.com/JuliaRegistries/General/pull/32136

**Comment by zzheng93** [comment] 2021-03-19 14:50
@SimonDanisch  Thank you!
