### ISSUE TITLE
Search funcition broken on Makie docs (returns 0 results)

### ISSUE THREAD

**Issue by nickkeepfer** [JuliaPlots/Makie.jl#1971] opened 2022-05-23 19:01 UTC
It seems the search function for the official Makie [docs](https://makie.juliaplots.org/) has broken

A search for any term returns zero results.

Navigation seems to be unaffected.

**Comment by kimlaberinto** [comment] 2022-05-23 19:06
Yup can confirm this experience of not returning anything for me as well.

For example: a search for Axis: https://makie.juliaplots.org/stable/search/index.html?q=Axis

**Comment by aramirezreyes** [comment] 2022-05-25 16:39
Can confirm

**Comment by ederag** [comment] 2022-05-25 18:44
Duplicate of #1965 ?

**Comment by SimonDanisch** [comment] 2022-05-26 14:27
Yes!

**Closed by SimonDanisch** 2022-05-26 14:27 UTC
