### ISSUE TITLE
Scrolling throws GLFWError (PLATFORM_ERROR): WGL: Failed to make context current: The handle is invalid.

### ISSUE THREAD

**Issue by bardo84** [JuliaPlots/Makie.jl#1361] opened 2021-10-04 11:34 UTC
After some mouse-wheel scrolling with y pressed, the following reproducible error happens:
```
julia> GLFWError (PLATFORM_ERROR): WGL: Failed to make context current: The handle is invalid. 
Stacktrace:
 [1] _ErrorCallbackWrapper(code::Int32, description::Cstring)
   @ GLFW C:\Users\nxp25875\.julia\packages\GLFW\BWxfF\src\callback.jl:43
 [2] MakeContextCurrent
   @ C:\Users\nxp25875\.julia\packages\GLFW\BWxfF\src\glfw3.jl:694 [inlined]
 [3] make_context_current
   @ C:\Users\nxp25875\.julia\packages\GLMakie\TViqo\src\drawing_primitives.jl:46 [inlined]
 [4] fps_renderloop(screen::GLMakie.Screen, framerate::Float64)
   @ GLMakie C:\Users\nxp25875\.julia\packages\GLMakie\TViqo\src\rendering.jl:26
 [5] renderloop(screen::GLMakie.Screen; framerate::Float64)
   @ GLMakie C:\Users\nxp25875\.julia\packages\GLMakie\TViqo\src\rendering.jl:48
 [6] renderloop(screen::GLMakie.Screen)
   @ GLMakie C:\Users\nxp25875\.julia\packages\GLMakie\TViqo\src\rendering.jl:41
 [7] (::GLMakie.var"#50#52"{GLMakie.Screen})()
   @ GLMakie .\task.jl:411
```

```
using GLMakie
GLMakie.activate!()

function makie_addsubplot(x, y; varargs...)  
    makie_addsubplot([], x, y; varargs...)
end

function makie_addsubplot(fap, x, y; legends = [], title = [], xlabel = [], ylabels = [])
    if isempty(fap)
        fig = Figure()
        ax = []
        pl = []
    else
        fig, ax, pl = fap
    end
    m = size(y, 2)
    if isempty(legends)
        legends = ["y$i" for i=1:m]
    end
    n = length(ax) + 1
    push!(ax, Axis(fig[n, 1]))
    linkxaxes!(ax...)
    # standard colors from matplotlib
    colors = ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd", "#8c564b", "#e377c2", "#7f7f7f", "#bcbd22", "#17becf"];
    for i = 1:m
        lines!(ax[n], x, y[:,i], label = legends[i], color = colors[(i-1)%10+1])
    end
    axislegend(ax[n])
    if !isempty(title)
        ax[1].title = title
    end
    if !isempty(xlabel)
        ax[end].xlabel = xlabel
    end
    hidexdecorations!.(ax[1:n-1], grid=false)
    rowgap!(fig.layout,0)
    display(fig)
    fap = (fig, ax, pl)
end

n = 100; m = 3
x = 1:n
y = randn(n,m)
fap = makie_addsubplot(x, cumsum(y[:,1]), legends = ["cumsum(toto)"])
fap = makie_addsubplot(fap, x, y, legends = ["toto", "titi", "tata"])
fap = makie_addsubplot(fap, x, y.^2, legends = ["toto2", "titi2", "tata2"], title = "A Title", xlabel = "Time [s]")
```

julia> VERSION
v"1.7.0-rc1"
(@v1.7) pkg> st
      Status `C:\Users\xxx\.julia\environments\v1.7\Project.toml`
  [6e4b80f9] BenchmarkTools v1.2.0
  [13f3f980] CairoMakie v0.6.5
  [e9467ef8] GLMakie v0.4.6
  [4b11ee91] Gaston v1.0.4
  [d0351b0e] InspectDR v0.4.3
  [c3a54625] JET v0.5.0
  [ee78f7c6] Makie v0.15.2
  [961ee093] ModelingToolkit v6.5.2
  [f0f68f2c] PlotlyJS v0.18.7
  [91a5bcdd] Plots v1.22.3
  [c46f51b8] ProfileView v0.6.10
  [295af30f] Revise v3.1.20
  [276b4fcb] WGLMakie v0.4.6

**Comment by SimonDanisch** [comment] 2021-10-04 11:47
Duplicate of: https://github.com/JuliaPlots/Makie.jl/issues/668

**Closed** 2021-10-04 11:50 UTC

**Comment by bardo84** [comment] 2021-10-04 11:52
Thanks for helping out!
