### ISSUE TITLE
Lines not show in GLMakie.jl

### ISSUE THREAD

**Issue by ValentinKaisermayer** [JuliaPlots/Makie.jl#2089] opened 2022-06-23 07:43 UTC
```julia
f = Figure()
ax = Axis(f[1,1])
lines!(cumsum(randn(100)))
scatter!(randn(100), randn(100))
f
```
![image](https://user-images.githubusercontent.com/50108075/175242556-ca79f355-54e4-4369-a14c-c84c9c0a3132.png)

The same is true if I activate GLMakie without display.
If I switch to CairoMakie I get this:
![plot_5](https://user-images.githubusercontent.com/50108075/175242744-6af108d3-e62c-4e48-9e2c-1fd95b610400.png)

```julia
julia> versioninfo()
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7 CPU         860  @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, nehalem)
Environment:
  JULIA_PKG_PRECOMPILE_AUTO = 1
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 8
```

[e9467ef8] GLMakie v0.6.7
Graphics card: ATI FirePro V3700 (FireGL)

**Comment by SimonDanisch** [comment] 2022-06-23 08:41
Duplicate of https://github.com/JuliaPlots/Makie.jl/issues/1460

**Comment by ValentinKaisermayer** [comment] 2022-06-23 12:07
Unfortunately it is a 2012 graphics cards with the latest driver being from 2015. Not sure how much you can do here.

**Comment by ArbitRandomUser** [comment] 2022-08-09 11:53
ive got access to 2 machines , 
one of them has an older fireprow2100 which is i believe is pre-vulkan .
This card can be run by two drivers one is the `radeon` kernel module and the other is the newer `amdgpu` kernel module , 
the `radeon` driver seems to be working fine , i haven't tested this device on the `amdgpu` driver. You might be likewise lucky. ( Then again you would have to use ubuntu 18.04 , i believe 20 and above default to `amdgpu`) you're mileage will vary .

**Closed** 2022-09-10 20:40 UTC
Labels: GLMakie
